#!/bin/sh
#
# chkconfig: 2345 85 15
# description: toastcontrollerd is toast controller watchdog.
# processname: toastcontrollerd
# config: /home/a/bin/toast/AgentDaemon.conf
# pidfile: /home/a/bin/toast/toast.pid

# Script Author: mulin.lyh, modify from haprxy service script
# Version: 20111223
# Source function library.
if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

# This is our service name
BASENAME=`basename $0`
if [ -L $0 ]; then
  BASENAME=`find $0 -name $BASENAME -printf %l`
  BASENAME=`basename $BASENAME`
fi

BASEPATH="path to toast controller"
RETVAL=0

start() {
  python "$BASEPATH$BASENAME".py start
  RETVAL=$?
  return $RETVAL
}

stop() {
  python "$BASEPATH$BASENAME".py stop
  RETVAL=$?
  return $RETVAL
}

restart() {
  python "$BASEPATH$BASENAME".py restart
  RETVAL=$?
  return $RETVAL
}

update() {
   python "$BASEPATH"toastupdate.py
   RETVAL=$?
   return $RETVAL
}

status(){
   python "$BASEPATH$BASENAME".py status
   RETVAL=$?
   return $RETVAL
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  update)
    update
    ;;
  status)
    status
    ;;
  *)
    echo $"Usage: $BASENAME {start|stop|update|restart|status}"
    exit 1
esac
exit $?
